language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

before_script:
  - composer self-update
  - composer install --prefer-source -n
  - php app/console doctrine:database:create
  - php app/console doctrine:schema:create

script: phpunit
