parameters:

services:
    kurl_shopify.shopify_client:
        class: Kurl\Bundle\ShopifyBundle\Service\ShopifyClient
        arguments: ["@request", "%kurl.shopify.wishlist.api_key%", "%kurl.shopify.wishlist.secret%"]
        public: true
        scope: request
